/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:fa04f334a240526e1c6c44bb82ed5d60:314dcc0ee8659f838e3fb58669ab5c76:28756f7154ae4c2d414233333f65cbda$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class OobiAnimation
	{
		public const string Oobi_Blink_Oobi_Blink_01 = "Oobi/Blink/Oobi_Blink_01";
		public const string Oobi_Blink_Oobi_Blink_02 = "Oobi/Blink/Oobi_Blink_02";
		public const string Oobi_Blink_Oobi_Blink_03 = "Oobi/Blink/Oobi_Blink_03";
		public const string Oobi_Blink_Oobi_Blink_04 = "Oobi/Blink/Oobi_Blink_04";
		public const string Oobi_Blink_Oobi_Blink_05 = "Oobi/Blink/Oobi_Blink_05";
		public const string Oobi_Death_Oobi_Death_01 = "Oobi/Death/Oobi_Death_01";
		public const string Oobi_Death_Oobi_Death_02 = "Oobi/Death/Oobi_Death_02";
		public const string Oobi_Death_Oobi_Death_03 = "Oobi/Death/Oobi_Death_03";
		public const string Oobi_Death_Oobi_Death_04 = "Oobi/Death/Oobi_Death_04";
		public const string Oobi_Death_Oobi_Death_05 = "Oobi/Death/Oobi_Death_05";
		public const string Oobi_Death_Oobi_Death_06 = "Oobi/Death/Oobi_Death_06";
		public const string Oobi_Death_Oobi_Death_07 = "Oobi/Death/Oobi_Death_07";
		public const string Oobi_Death_Oobi_Death_08 = "Oobi/Death/Oobi_Death_08";
		public const string Oobi_DropCollect_Oobi_DropCollect_01 = "Oobi/DropCollect/Oobi_DropCollect_01";
		public const string Oobi_DropCollect_Oobi_DropCollect_02 = "Oobi/DropCollect/Oobi_DropCollect_02";
		public const string Oobi_DropCollect_Oobi_DropCollect_03 = "Oobi/DropCollect/Oobi_DropCollect_03";
		public const string Oobi_Idle_Oobi_Idle_01 = "Oobi/Idle/Oobi_Idle_01";
		public const string Oobi_Idle_Oobi_Idle_02 = "Oobi/Idle/Oobi_Idle_02";
		public const string Oobi_TakeDamage_Oobi_TakeDamage_01 = "Oobi/TakeDamage/Oobi_TakeDamage_01";
		public const string Oobi_TakeDamage_Oobi_TakeDamage_02 = "Oobi/TakeDamage/Oobi_TakeDamage_02";
		public const string Oobi_TakeDamage_Oobi_TakeDamage_03 = "Oobi/TakeDamage/Oobi_TakeDamage_03";
		public const string Plane_Plane_001 = "Plane/Plane_001";
		public const string Plane_Plane_003 = "Plane/Plane_003";
		public const string Plane_Plane_005 = "Plane/Plane_005";
		public const string Plane_Plane_007 = "Plane/Plane_007";
		public const string Plane_Plane_009 = "Plane/Plane_009";
		public const string Plane_Plane_011 = "Plane/Plane_011";
		public const string Plane_Plane_013 = "Plane/Plane_013";
		public const string Plane_Plane_015 = "Plane/Plane_015";
		public const string Plane_Plane_017 = "Plane/Plane_017";
		public const string Plane_Plane_019 = "Plane/Plane_019";
		public const string Plane_Plane_021 = "Plane/Plane_021";
		public const string Plane_Plane_023 = "Plane/Plane_023";
		public const string Plane_Plane_025 = "Plane/Plane_025";
		public const string Plane_Plane_027 = "Plane/Plane_027";
		public const string Plane_Plane_029 = "Plane/Plane_029";
		public const string Plane_Plane_031 = "Plane/Plane_031";
		public const string Plane_Plane_033 = "Plane/Plane_033";
		public const string Plane_Plane_035 = "Plane/Plane_035";
		public const string Plane_Plane_037 = "Plane/Plane_037";
		public const string Plane_Plane_039 = "Plane/Plane_039";
		public const string Remover_Clap1 = "Remover/Clap1";
		public const string Remover_Clap3 = "Remover/Clap3";
		public const string Remover_Clap5 = "Remover/Clap5";
		public const string Remover_Clap7 = "Remover/Clap7";
		public const string Remover_Clap9 = "Remover/Clap9";
		public const string Remover_Clap11 = "Remover/Clap11";
		public const string Remover_Clap13 = "Remover/Clap13";
		public const string Remover_Clap15 = "Remover/Clap15";
		public const string Remover_Clap17 = "Remover/Clap17";
		public const string Remover_Clap19 = "Remover/Clap19";
		public const string WaterDrop_Drop_Animations_Drop_Idle_01 = "WaterDrop/Drop_Animations/Drop_Idle_01";
		public const string WaterDrop_Drop_Animations_Drop_Idle_02 = "WaterDrop/Drop_Animations/Drop_Idle_02";
		public const string WaterDrop_Drop_Animations_Drop_Idle_03 = "WaterDrop/Drop_Animations/Drop_Idle_03";
		public const string WaterDrop_Drop_Animations_Drop_Idle_04 = "WaterDrop/Drop_Animations/Drop_Idle_04";
		public const string WaterDrop_Drop_Animations_Drop_Idle_05 = "WaterDrop/Drop_Animations/Drop_Idle_05";
		public const string WaterDrop_Drop_Animations_Drop_Idle_06 = "WaterDrop/Drop_Animations/Drop_Idle_06";
		public const string WaterDrop_Drop_Animations_Drop_Idle_07 = "WaterDrop/Drop_Animations/Drop_Idle_07";
		public const string WaterDrop_Drop_Animations_Drop_Idle_08 = "WaterDrop/Drop_Animations/Drop_Idle_08";
		public const string WaterDrop_Drop_Animations_Drop_Idle_09 = "WaterDrop/Drop_Animations/Drop_Idle_09";
		public const string WaterDrop_Drop_Animations_Drop_Idle_10 = "WaterDrop/Drop_Animations/Drop_Idle_10";
		public const string WaterDrop_Drop_Animations_Drop_Idle_11 = "WaterDrop/Drop_Animations/Drop_Idle_11";
		public const string WaterDrop_Splash_Animations_Drop_Splash_01 = "WaterDrop/Splash_Animations/Drop_Splash_01";
		public const string WaterDrop_Splash_Animations_Drop_Splash_02 = "WaterDrop/Splash_Animations/Drop_Splash_02";
		public const string WaterDrop_Splash_Animations_Drop_Splash_03 = "WaterDrop/Splash_Animations/Drop_Splash_03";
		public const string WaterDrop_Splash_Animations_Drop_Splash_04 = "WaterDrop/Splash_Animations/Drop_Splash_04";
		public const string WaterDrop_Splash_Animations_Drop_Splash_05 = "WaterDrop/Splash_Animations/Drop_Splash_05";
		public const string WaterDrop_Splash_Animations_Drop_Splash_06 = "WaterDrop/Splash_Animations/Drop_Splash_06";
		public const string WaterDrop_Splash_Animations_Drop_Splash_07 = "WaterDrop/Splash_Animations/Drop_Splash_07";
		public const string WaterDrop_Splash_Animations_Drop_Splash_08 = "WaterDrop/Splash_Animations/Drop_Splash_08";
	}
}